export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_WEATHER = 'GET_WEATHER';
export const DELETE_WEATHER = 'DELETE_WEATHER';
export const NOT_ACCESS = 'NOT_ACCESS';
;

export default {
    GET_CURRENT_WEATHER,
    GET_WEATHER,
    DELETE_WEATHER,
    NOT_ACCESS
}
